### ISSUE TITLE
Error on publishing assets

### ISSUE THREAD

**Issue by thedevsbuddy** [InfyOmLabs/laravel-payumoney#1]
While publishing assets i am getting this error.
 

  ErrorException 

  copy({PROECT_PATH}\vendor/infyomlabs/laravel-payumoney/assets/infyom-logo.png): failed to open stream: No such file or directory

  at  {PROECT_PATH}\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:302
    298▕      * @return bool
    299▕      */
    300▕     public function copy($path, $target)
    301▕     {
  ➜ 302▕         return copy($path, $target);
    303▕     }
    304▕
    305▕     /**
    306▕      * Create a symlink to the target file or directory. On Windows, a hard link is created if the target is a file.

  1   {PROECT_PATH}\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:302
      copy(" {PROECT_PATH}\vendor/infyomlabs/laravel-payumoney/assets/infyom-logo.png", " {PROECT_PATH}\public\
payumoney/infyom-logo.png")

  2    {PROECT_PATH}\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:261
      Illuminate\Filesystem\Filesystem::copy(" {PROECT_PATH}\vendor/infyomlabs/laravel-payumoney/assets/infyom-logo.png", " {PROECT_PATH}\public\payumoney/infyom-logo.png")

**Comment by vishalinfyom** [comment]
Hello @thedevsbuddy we will look into this and get back to you.

Thanks

**Comment by vishalinfyom** [comment]
Hello @thedevsbuddy we have fixed the issue into our latest build.

`composer require infyomlabs/laravel-payumoney:"^1.3.0"`

Thanks
